---
name: chess-blindfold
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Setup Stockfish
        run: |
          chmod +x setup.sh
          ./setup.sh
      - name: Build the app
        run: npm run build
      - name: Build Library
        run: |
          mkdir -p serve_content/chess-blindfold
          cp -r serve_content/prod/* serve_content/chess-blindfold
          cp -r serve_content/shared/* serve_content/chess-blindfold
          cp serve_content/index_prod.html serve_content/chess-blindfold/index.html
          cd serve_content/chess-blindfold
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: serve_content/chess-blindfold
          publish_branch: gh-pages
          force_orphan: true
